### ISSUE TITLE
Android x86 build crashes on Android 4.4 emulator

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3409]
* KOReader version: todays git
* Device: pc x86 (x86 android 4.4 emulator without Gapps)

#### Issue
x86 Koreader todays build crash

#### Steps to reproduce
> ANDROID_ARCH=x86 ./kodev release android
adb install koreader-android-i686-linux-android-v2015.11-1370-g5ee6c01.apk

Start koreader on device - "Unfortunatelly, Koreader has stopped."

##### `crash.log` (if applicable)

>$ ./kodev log android
--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
I/luajit-launcher( 2218): Waiting for app ready...
I/luajit-launcher( 2218): App window ready.
I/luajit-launcher( 2218): App gained focus.
I/luajit-launcher( 2218): Launching LuaJIT assets...
I/luajit-launcher( 2218): get screen width  768
I/luajit-launcher( 2218): get screen height  1280
I/luajit-launcher( 2218): Application data directory /data/data/org.koreader.launcher/files
I/luajit-launcher( 2218): Application library directory /data/app-lib/org.koreader.launcher-1
I/luajit-launcher( 2218): Screen size 768x1280
I/luajit-launcher( 2218): Screen brightness 102

this seems to provide more usefull information  `$ adb logcat ` :
(..)
>I/luajit-launcher( 2218): Screen size 768x1280
I/luajit-launcher( 2218): Screen brightness 102
F/libc    ( 2218): Fatal signal 8 (SIGFPE) at 0xb778bac8 (code=1), thread 2230 (reader.launcher)
I/ActivityManager( 1555): Displayed org.koreader.launcher/.MainActivity: +199ms
D/EGL_emulation( 1630): eglMakeCurrent: 0xb92cd9d0: ver 2 0
I/DEBUG   ( 1136): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 1136): Build fingerprint: 'generic_x86/sdk_x86/generic_x86:4.4.2/KK/4174703:eng/test-keys'
I/DEBUG   ( 1136): Revision: '0'
I/DEBUG   ( 1136): pid: 2218, tid: 2230, name: reader.launcher  >>> org.koreader.launcher <<<
I/DEBUG   ( 1136): signal 8 (SIGFPE), code -6 (SI_TKILL), fault addr 000008aa
I/AndroidRuntime( 2206): VM exiting with result code 0.
D/EGL_emulation( 1630): eglMakeCurrent: 0xb92cd9d0: ver 2 0
I/DEBUG   ( 1136):     eax 0f0deb4c  ebx b77a4fe4  ecx 00000070  edx 00000000
I/DEBUG   ( 1136):     esi 00000000  edi b7781004
I/DEBUG   ( 1136):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   ( 1136):     eip b778bac8  ebp b64a8e70  esp 96e96ae0  flags 00210246
E/Corkscrew( 1136): unrecognized dwarf lower part encoding: 0xb2
I/DEBUG   ( 1136): 
I/DEBUG   ( 1136): backtrace:
I/DEBUG   ( 1136):     #00  pc 00006ac8  /system/bin/linker (__dl__Z19dlsym_linear_lookupPKcPP6soinfoS2_+216)
I/DEBUG   ( 1136):     #01  pc 00001265  /system/bin/linker (__dl_dlsym+325)
I/DEBUG   ( 1136):     #02  pc 00069e61  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):     #03  pc 00007739  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136): 
I/DEBUG   ( 1136): stack:
I/DEBUG   ( 1136):          96e96aa0  00000000  
I/DEBUG   ( 1136):          96e96aa4  96d791f0  
I/DEBUG   ( 1136):          96e96aa8  e1828144  
I/DEBUG   ( 1136):          96e96aac  22000073  
I/DEBUG   ( 1136):          96e96ab0  00000000  
I/DEBUG   ( 1136):          96e96ab4  96e96af0  [stack:2230]
I/DEBUG   ( 1136):          96e96ab8  0000000a  
I/DEBUG   ( 1136):          96e96abc  96f26bf8  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96ac0  96e96b4c  [stack:2230]
I/DEBUG   ( 1136):          96e96ac4  96d791f0  
I/DEBUG   ( 1136):          96e96ac8  96e96b4c  [stack:2230]
I/DEBUG   ( 1136):          96e96acc  96eaea2c  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96ad0  96d791c0  
I/DEBUG   ( 1136):          96e96ad4  96d96e28  
I/DEBUG   ( 1136):          96e96ad8  0000000c  
I/DEBUG   ( 1136):          96e96adc  b778bb11  /system/bin/linker (__dl__Z19dlsym_linear_lookupPKcPP6soinfoS2_+289)
I/DEBUG   ( 1136):     #00  96e96ae0  b523caee  /system/lib/libRScpp.so
I/DEBUG   ( 1136):          96e96ae4  96d97340  
I/DEBUG   ( 1136):          96e96ae8  96d713b0  
I/DEBUG   ( 1136):          96e96aec  b779bb06  /system/bin/linker (__dl_pthread_mutex_lock+198)
I/DEBUG   ( 1136):          96e96af0  96f0cd52  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96af4  96f0cd52  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96af8  96f0cd52  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96afc  00000000  
I/DEBUG   ( 1136):          96e96b00  00000000  
I/DEBUG   ( 1136):          96e96b04  00000000  
I/DEBUG   ( 1136):          96e96b08  0f0deb4c  
I/DEBUG   ( 1136):          96e96b0c  b779f590  /system/bin/linker
I/DEBUG   ( 1136):          96e96b10  96d791c0  
I/DEBUG   ( 1136):          96e96b14  96d791c0  
I/DEBUG   ( 1136):          96e96b18  b778b9f9  /system/bin/linker (__dl__Z19dlsym_linear_lookupPKcPP6soinfoS2_+9)
I/DEBUG   ( 1136):          96e96b1c  b77a4fe4  /system/bin/linker
I/DEBUG   ( 1136):          ........  ........
I/DEBUG   ( 1136):     #01  96e96b30  96d97340  
I/DEBUG   ( 1136):          96e96b34  96e96b4c  [stack:2230]
I/DEBUG   ( 1136):          96e96b38  00000000  
I/DEBUG   ( 1136):          96e96b3c  96f00770  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96b40  96d791c0  
I/DEBUG   ( 1136):          96e96b44  fffffffe  
I/DEBUG   ( 1136):          96e96b48  96d692b0  
I/DEBUG   ( 1136):          96e96b4c  00000000  
I/DEBUG   ( 1136):          96e96b50  00000000  
I/DEBUG   ( 1136):          96e96b54  96d791f0  
I/DEBUG   ( 1136):          96e96b58  00000064  
I/DEBUG   ( 1136):          96e96b5c  96f26bf8  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96b60  96d791c0  
I/DEBUG   ( 1136):          96e96b64  96d692b0  
I/DEBUG   ( 1136):          96e96b68  96d791c0  
I/DEBUG   ( 1136):          96e96b6c  96f00e62  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):     #02  96e96b70  ffffffff  
I/DEBUG   ( 1136):          96e96b74  96d97340  
I/DEBUG   ( 1136):          96e96b78  96d692b0  
I/DEBUG   ( 1136):          96e96b7c  96eb2f5c  /data/app-lib/org.koreader.launcher-1/libluajit.so (lua_getfield+108)
I/DEBUG   ( 1136):          96e96b80  96d79d58  
I/DEBUG   ( 1136):          96e96b84  96d792c8  
I/DEBUG   ( 1136):          96e96b88  96f00d80  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96b8c  96e9e73a  /data/app-lib/org.koreader.launcher-1/libluajit.so
I/DEBUG   ( 1136):          96e96b90  96d791c0  
I/DEBUG   ( 1136):          96e96b94  96d692b0  
I/DEBUG   ( 1136):          96e96b98  96d692b0  
I/DEBUG   ( 1136):          96e96b9c  96eb28a9  /data/app-lib/org.koreader.launcher-1/libluajit.so (lua_pushstring+73)
I/DEBUG   ( 1136):          96e96ba0  96d791c0  
I/DEBUG   ( 1136):          96e96ba4  96d692b0  
I/DEBUG   ( 1136):          96e96ba8  96d791c0  
I/DEBUG   ( 1136):          96e96bac  96f26bf8  /data/app-lib/org.koreader.launcher-1/libluajit.so
E/JavaBinder( 1555): !!! FAILED BINDER TRANSACTION !!!
W/InputDispatcher( 1555): channel 'a5589fc8 org.koreader.launcher/org.koreader.launcher.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1555): channel 'a5589fc8 org.koreader.launcher/org.koreader.launcher.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/Zygote  ( 1139): Process 2218 terminated by signal (8)
D/gralloc_ranchu( 1138): gralloc_alloc: Creating ashmem region of size 716800
D/        ( 1555): HostConnection::get() New Host Connection established 0xb947edc0, tid 2234
W/        ( 1555): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 
W/ActivityManager( 1555):   Force finishing activity org.koreader.launcher/.MainActivity
W/InputDispatcher( 1555): Attempted to unregister already unregistered input channel 'a5589fc8 org.koreader.launcher/org.koreader.launcher.MainActivity (server)'
I/WindowState( 1555): WIN DEATH: Window{a5589fc8 u0 org.koreader.launcher/org.koreader.launcher.MainActivity}
D/dalvikvm( 1555): GC_CONCURRENT freed 81K, 41% free 7033K/11820K, paused 2ms+1ms, total 11ms
D/dalvikvm( 1555): WAIT_FOR_CONCURRENT_GC blocked 6ms
I/dalvikvm-heap( 1555): Grow heap (frag case) to 7.354MB for 380492-byte allocation
D/dalvikvm( 1555): GC_FOR_ALLOC freed 4K, 40% free 7400K/12192K, paused 11ms, total 11ms
W/ActivityManager( 1555): Exception thrown during pause
W/ActivityManager( 1555): android.os.DeadObjectException
W/ActivityManager( 1555):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager( 1555):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager( 1555):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager( 1555):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2455)
W/ActivityManager( 1555):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2329)
W/ActivityManager( 1555):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2035)
W/ActivityManager( 1555):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9543)
W/ActivityManager( 1555):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9436)
W/ActivityManager( 1555):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10081)
W/ActivityManager( 1555):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9632)
W/ActivityManager( 1555):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager( 1555): Process org.koreader.launcher (pid 2218) has died.
D/dalvikvm( 1555): GC_FOR_ALLOC freed 430K, 42% free 7119K/12192K, paused 9ms, total 9ms
D/EGL_emulation( 1860): eglMakeCurrent: 0xb931a250: ver 2 0
I/dalvikvm-heap( 1555): Grow heap (frag case) to 8.150MB for 1127532-byte allocation
D/dalvikvm( 1555): GC_FOR_ALLOC freed 1K, 39% free 8219K/13296K, paused 8ms, total 8ms
D/dalvikvm( 1555): GC_CONCURRENT freed 5K, 38% free 8311K/13296K, paused 2ms+1ms, total 15ms
D/gralloc_ranchu( 1138): gralloc_alloc: Creating ashmem region of size 651264
D/        ( 1138): HostConnection::get() New Host Connection established 0xb7bbe010, tid 2237
W/        ( 1138): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 
D/        ( 1555): HostConnection::get() New Host Connection established 0xb94804b0, tid 1570
D/EGL_emulation( 1860): eglMakeCurrent: 0xb931a250: ver 2 0
W/        ( 1555): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 
E/EGL_emulation( 1860): tid 1860: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
W/HardwareRenderer( 1860): Backbuffer cannot be preserved
D/gralloc_ranchu( 1138): gralloc_alloc: Creating ashmem region of size 651264
D/gralloc_ranchu( 1138): gralloc_alloc: Creating ashmem region of size 651264
D/        ( 1138): HostConnection::get() New Host Connection established 0xb7bb7940, tid 2238
W/        ( 1138): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 
E/SoundPool( 1555): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/KeypressStandard.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/KeypressStandard.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/KeypressSpacebar.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/KeypressSpacebar.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/KeypressDelete.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/KeypressDelete.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/KeypressReturn.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/KeypressReturn.ogg
E/SoundPool( 1555): error loading /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService( 1555): Soundpool could not load file: /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService( 1555): onLoadSoundEffects(), Error -1 while loading samples
W/Binder  ( 1720): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 1720): java.lang.NullPointerException
W/Binder  ( 1720):      at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 1720):      at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 1720):      at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 1720):      at dalvik.system.NativeStart.run(Native Method)
W/InputMethodManagerService( 1555): Got RemoteException sending setActive(false) notification to pid 2218 uid 10052
D/EGL_emulation( 1630): eglMakeCurrent: 0xb92cd9d0: ver 2 0
D/dalvikvm( 1555): GC_CONCURRENT freed 1216K, 38% free 8344K/13292K, paused 0ms+1ms, total 8ms
D/dalvikvm( 1738): GC_CONCURRENT freed 463K, 17% free 3415K/4076K, paused 1ms+1ms, total 3ms
^[[B^C

**Comment by mwoz123** [comment]
arm version build using :
> cd platform/android/luajit-launcher && ./mk-luajit.sh clean
cd -
./kodev release android
adb install koreader-android-arm-linux-androideabi-v2015.11-1370-g5ee6c01.apk

Runs without any problems

**Comment by Frenzie** [comment]
Interesting.

> Runs without any problems on ARM android 7.0 emulator with GApps

That's an odd comparison to make. Anyway, if it's just testing you're concerned about run it in 5+.

**Comment by Frenzie** [comment]
As an aside, on API 16 (Android 4.1) this doesn't occur, leading me to think it's probably a bug in the Android Bionic linker on 4.4 specifically. However, I do get this issue:

```
E/luajit-launcher( 1937): Failed to run script: frontend/cache.lua:46: cannot open /mnt/sdcard/koreader/cache/: Permission denied
```

Is there such a thing as <5 x86 devices of interest?

On API 10 (2.3) there's another error still:

```
E/AndroidRuntime( 1487): FATAL EXCEPTION: Thread-10
E/AndroidRuntime( 1487): java.lang.NoSuchMethodError: android.view.Display.getSize
E/AndroidRuntime( 1487): 	at org.koreader.launcher.MainActivity.getSceenSize(MainActivity.java:246)
E/AndroidRuntime( 1487): 	at org.koreader.launcher.MainActivity.getScreenWidth(MainActivity.java:255)
E/AndroidRuntime( 1487): 	at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager( 1219):   Force finishing activity org.koreader.launcher/.MainActivity
```

That should be easy enough to get around (see, e.g., [here](https://stackoverflow.com/q/11647817/2470572)), but this should also be an issue on ARM. Introduced by https://github.com/koreader/android-luajit-launcher/pull/56

There might be a way to partially test against such regressions on CircleCI or Travis on the android-luajit-launcher repo. https://circleci.com/mobile/android/ https://docs.travis-ci.com/user/languages/android/

**Comment by Frenzie** [comment]
Closing since for x86 it's not worth the effort.
