### ISSUE TITLE
macos build broken by commit 5df25f8

### ISSUE THREAD

**Issue by rexkerr** [koreader/koreader#7307]
* KOReader version: 2021.02 pre-release nightlies
* Device:  MacOS development build

#### Issue

As of commit 5df25f8bd60d17d7547d75b019082ae5edd65f38, the macos build is broken, with the following error:

```
[ 12%] Linking CXX executable sdcv
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_iconv_open", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
My best guess, looking at the diffs, is that it's the change from GetText 0.20.1 to 0.21 in base commit b1abca63443875ab9aeea83097611c50bee4de69

#### Steps to reproduce

Check out any commit on master at or after the referenced commit, run kodev build

**Comment by Frenzie** [comment]
Also see https://gitter.im/koreader/koreader?at=602af0ebe634904e60a0ecec

**Comment by NiLuJe** [comment]
On macOS, we also have the possibility of dropping our own gettext build and using brew's, since it's already in the dep list, IIRC.

I'm pretty sure my own macOS system is too old to trip this, so, PRs welcome ;).

**Comment by rexkerr** [comment]
I'll spend a little bit of time on it, but am considering just installing a Linux VM and doing my development there, it's so much easier anyhow, and I prefer a tiling WM when doing actual work. :)
