### ISSUE TITLE
Better download backend in NewsDownloader 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3516]
* KOReader version: git
* Device: all

#### Issue

I'm trying to find better backend for download html files in News Downloader plugin.
Current implementation got problems e.g. with 302 (redirect) http statuses.

**Any proposal what could be used?**

Ideal candidate requirements:
1. can handle 302 (redirect) http statuses
2. ability to download html file with images + ability to update links to images to downloaded folder.
3. ability to create mhtml file (need to check if koreader supports it? it's not on the [list](https://github.com/koreader/koreader/wiki/Features-list) but html is also not there.)
4. more?

What I found till now:
a) [wget-lua](https://github.com/alard/wget-lua)
b) [lua-cURL](https://github.com/Lua-cURL/Lua-cURLv3)
c) [luakit browser](https://github.com/luakit/luakit)

But none of them seems to complete all requirements.

**Comment by Frenzie** [comment]
Only luasec has an issue with redirects (i.e., only https). I've been thinking about replacing it with lua-http.

**Comment by Frenzie** [comment]
> ability to download html file with images + ability to update links to images to downloaded folder.

That sounds trivial. Why would any heavy external requirement be needed for that?

> ability to create mhtml file (need to check if koreader supports it? it's not on the list but html is also not there.)

MHTML is a superset of HTML, while HTML is a subset of EPUB. In other words, I doubt it. But this supposed requirement needs to be scrutinized regardless. I assume you have a goal in mind, presumably to stick everything in a single file. MHTML is a potential step toward that goal. Within our context, EPUB seems much more logical than MHTML as a single-file format. (Also see [here](http://www.catb.org/~esr/faqs/smart-questions.html#goal).)

**Comment by AlanSP1** [comment]
Could koreader be made to produce epub files? I mean, I know that everything can be made, but is it fairly easy, or is it pretty complex?

**Comment by KenMaltby** [comment]
KOReader has been able to handle HTML very well, in fact I have used it for very large manuals, in the past, where it handled the large manual better that way than in epub.

**Comment by Frenzie** [comment]
@AlanSP1 It already does. Try downloading a full Wikipedia article. ;-)

**Comment by mwoz123** [comment]
> That sounds trivial. Why would any heavy external requirement be needed for that?

wow, it seems hardcore for me (in lua). I didn't want to reinvent the wheel, so decided to ask for specialized tool.

> MHTML is a superset of HTML, while HTML is a subset of EPUB. In other words, I doubt it. But this supposed requirement needs to be scrutinized regardless. I assume you have a goal in mind, presumably to stick everything in a single file. MHTML is a potential step toward that goal. Within our context, EPUB seems much more logical than MHTML as a single-file format. (Also see here.)

Right, I thought MHTML is rather a standard but looking deeper seems it's not:(

I want a "web-browser like backed" that would be able to handle different http scenarios (today we want http redirect, tomorow we might want http authorization, or something else?). 
I wanted a good one, so we wouldn't have to change the backend again (at least not too fast).

Right I wanted to have it all in one file (separate folders/extra file in the same folder will create a mess in feed news folder). 

I thought a specialized web-browser backend would be able to handle http(s) and so the mhtml seemed a natural choice (as I'd thought we could find a tool that can also store to mhtml). So we could have one external tool...

I didn't think about Epub. It seems good idea..
But would require probably more coding..

I'd done some checks and from above list had wget seemed the best option, for then..
But I'll have to look at your suggestion [lua-http](https://github.com/daurnimator/lua-http)..

Any other tools to add to list?

**Comment by Frenzie** [comment]
> wow, it seems hardcore for me (in lua). I didn't want to reinvent the wheel, so decided to ask for specialized tool.

At its most trivial you can just match `<img>` and pick a `src` from that. Less trivially (i.e., not reinventing the wheel) you'd just switch to a full HTML parser, such as lua-htmlparser, in which case it'd still be almost as trivial to retrieve the same thing.

> Right, I thought MHTML is rather a standard but looking deeper seems it's not:(

I'm pretty sure it's an ISO standard, or at least the e-mail format it's based on is. That doesn't really change anything though.

> I want a "web-browser like backed" that would be able to handle different http scenarios (today we want http redirect, tomorow we might want http authorization, or something else?).

We already do all of those things, including "something else." :-P

> I didn't think about Epub. It seems good idea..
But would require probably more coding..

You'll have to explain that one to me.

> I thought a specialized web-browser backend would be able to handle http(s) and so the mhtml seemed a natural choice (as I'd thought we could find a tool that can also store to mhtml). So we could have one external tool...

One external tool that's bigger than the entire program. :-P

That could be discussed in the EPUB3-rendering sense. (E.g., Readium.)

**Comment by Frenzie** [comment]
> Is there a way to replace *.so files with *.lua files as it should work on other architecture devices?

If it's just to test write some Lua code that may not be necessary, but to properly include it the whole thing would need to be part of the build process in base.

See, e.g., https://github.com/koreader/koreader-base/blob/35045d144cb0d747632c0a819ff4b7b4ddd0ee75/Makefile.third#L407-L437 and https://github.com/koreader/koreader-base/blob/35045d144cb0d747632c0a819ff4b7b4ddd0ee75/thirdparty/lua-Spore/CMakeLists.txt

**Comment by mwoz123** [comment]
I don't know Makefiles. So I asked my mate (who knows it a little bit) for help.

Could you check if it makes sense:
https://github.com/mwoz123/koreader-base/commit/a76fd02db0e5ee159616f0eefdd268f95d34ec4f

BTW how to refresh/reforce the 'fetch-thrirdparty' ? 
Cause it doesn't:
```
$ ./kodev  fetch-thirdparty
git submodule init
git submodule sync
Synchronizing submodule url for 'base'
Synchronizing submodule url for 'platform/android/luajit-launcher'
Synchronizing submodule url for 'platform/ubuntu-touch/ubuntu-touch-sdl'
Synchronizing submodule url for 'resources/fonts'
Synchronizing submodule url for 'test'
git submodule update
make -C base fetchthirdparty
make[1]: Entering directory '/media/marcin/Dane1/koreader/base'
git submodule init
git submodule sync
Synchronizing submodule url for 'luafilesystem'
Synchronizing submodule url for 'thirdparty/kpvcrlib/crengine'
git submodule foreach --recursive git reset --hard
Entering 'luafilesystem'
HEAD is now at 6d039ff Merge pull request #53 from Tieske/fix_warning
Entering 'thirdparty/kpvcrlib/crengine'
HEAD is now at e1a417f epub.css: display <pre> and <code> with a monospace font (#191)
git submodule update
cleaning up crengine checkout...
make[1]: Leaving directory '/media/marcin/Dane1/koreader/base'
marcin@dell:/media/marcin/Dane1/koreader$ 
```

**Comment by Frenzie** [comment]
There are a couple of things in there that don't really seem to make much sense at a glance (like the LUA_HTTP_VER thing) but the one I presume is troubling you most atm is that you need to add it to the list of thirdparty libs that are actually built:

https://github.com/mwoz123/koreader-base/blob/a76fd02db0e5ee159616f0eefdd268f95d34ec4f/Makefile.defs#L650

**Comment by mwoz123** [comment]
lua-http added to `Makefile.defs` see git diff (bottom of log) but `./kodev fetch-thirdparty` still not building lua-http (even after `./kodev clean`)

 


```
$ ./kodev fetch-thirdparty
git submodule init
git submodule sync
Synchronizing submodule url for 'base'
Synchronizing submodule url for 'platform/android/luajit-launcher'
Synchronizing submodule url for 'platform/ubuntu-touch/ubuntu-touch-sdl'
Synchronizing submodule url for 'resources/fonts'
Synchronizing submodule url for 'test'
git submodule update
make -C base fetchthirdparty
make[1]: Entering directory '/media/marcin/Dane1/koreader/base'
git submodule init
git submodule sync
Synchronizing submodule url for 'luafilesystem'
Synchronizing submodule url for 'thirdparty/kpvcrlib/crengine'
git submodule foreach --recursive git reset --hard
Entering 'luafilesystem'
HEAD is now at 6d039ff Merge pull request #53 from Tieske/fix_warning
Entering 'thirdparty/kpvcrlib/crengine'
HEAD is now at e1a417f epub.css: display <pre> and <code> with a monospace font (#191)
git submodule update
cleaning up crengine checkout...
make[1]: Leaving directory '/media/marcin/Dane1/koreader/base'
marcin@dell:/media/marcin/Dane1/koreader$ cd base/
marcin@dell:/media/marcin/Dane1/koreader/base$ git diff
diff --git a/Makefile.defs b/Makefile.defs
index 29a3725..efebdc4 100644
--- a/Makefile.defs
+++ b/Makefile.defs
@@ -647,4 +647,4 @@ LPEG_RE=$(OUTPUT_DIR)/rocks/share/lua/5.1/re.lua
 LPEG_DYNLIB=$(OUTPUT_DIR)/rocks/lib/lua/5.1/lpeg.so
 
 
-CMAKE_THIRDPARTY_LIBS=kpvcrlib,evernote-sdk-lua,luajit,lpeg,turbo,zsync,zyre,czmq,filemq,libk2pdfopt,tesseract,leptonica,lua-Spore,sdcv,luasec,luasocket,libffi,lua-serialize,glib,lodepng,minizip,djvulibre,openssl,mupdf,libzmq,freetype2,giflib,libpng,zlib,tar,libiconv,gettext,libjpeg-turbo,popen-noshell,nanosvg,dropbearmulti
+CMAKE_THIRDPARTY_LIBS=kpvcrlib,evernote-sdk-lua,luajit,lpeg,turbo,zsync,zyre,czmq,filemq,libk2pdfopt,tesseract,leptonica,lua-Spore,sdcv,luasec,luasocket,libffi,lua-serialize,glib,lodepng,minizip,djvulibre,openssl,mupdf,libzmq,freetype2,giflib,libpng,zlib,tar,libiconv,gettext,libjpeg-turbo,popen-noshell,nanosvg,dropbearmulti,lua-http
```

**Comment by Frenzie** [comment]
You shouldn't normally need to clean or "force" anything.

The commit you showed me earlier could never succeed because it's full of undefined variables. My apologies for not stating that more clearly. I pointed out what I consider the tricky part, whereas the fact that you need to define variables or they'll just be empty… that's not really a secret or tricky. ;-)

You can see a full example here: https://github.com/koreader/koreader-base/pull/640/files (Ignore all the patch stuff at the end.)

Adding a new library normally isn't too hard, but there is a fairly significant time investment involved in tweaking the specifics. Unfortunately it's not the kind of thing one can just do in ten minutes. Particularly in this case where lua-http has a number of [dependencies](https://github.com/daurnimator/lua-http#dependencies).

Architecturally speaking I've been wondering if it would make sense to leverage luarocks itself during the build process for the various rocks, e.g. along these lines:

https://github.com/koreader/koreader/blob/4c8ef614778fa33f22a8d67557e077524224417f/.ci/install.sh#L26-L36

Because that would make it simple to add other rocks to the mix. But on the flipside, we might still need to customize the rocks too much to make it work on various platforms (mostly Android & Mac) to make that worthwhile.

I've been pondering that without really reaching a decision. In short, that's why I haven't yet decided to invest the few hours necessary to add a new library like lua-http. :-)

**Comment by mwoz123** [comment]
Ok. So you're saying I need C/c++ knowledge to add library? And won't be able to do it without? :(

This will means I'll have to wait until someone else does it :(

Unless this can be done other way?
I glanced at lua rocks, as you wrote. 
Can it be used to add only list of lua-http dependencies?
If we then "compile" only lua-http will it work on all platforms? As I'm using Android I'm mainly interested in that. So maybe it will be easier and doesn't require c/c++ knowledge, so I'll be able to do it( or with a little help) ?

**Comment by Frenzie** [comment]
> So you're saying I need C/c++ knowledge to add library?

No, those patches are not directly related but that PR shows each and every Makefile thing that would need changing.

> I glanced at lua rocks, as you wrote.
Can it be used to add only list of lua-http dependencies?

We don't have luarocks. I'm not even sure if it plays nice with cross-compiling at this point.

**Comment by mwoz123** [comment]
I did some analysis and I ask for help on LuaRock. 

It seems LuaRocks can build & compile all dependencies even for CrossCompile.

Command line (ubuntu 18.04) for this would be something like: 
`$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" CFLAGS="-I/usr/include/x86_64-linux-gnu -I/usr/include/lua5.3"  --local`

(this is for ubuntu  repo arm-linux gcc compiler)

Error here for building compat53 (`http 0.2-1 depends on compat53 >= 0.3 (not installed)` (required for lua  < 5.3)
```
 ‘_Float128’ is not supported on this target
```
I was repeated couple times. 
For the compiler used in koreader I'd different (more complicated)  error. so not attaching now) 

I commented out this dependecy (in [http-scm-0.rockspec](https://github.com/daurnimator/lua-http/blob/master/http-scm-0.rockspec)) and tried to build with lua5.3 but then I'd the same error (repeated even more times) for `_Float64x` and `_Float128` during other dependecy (`cqueues` ) build 

Previously I tried to compile manually for ARM `cqueues` from github. 
In Makefile I did replaced `gmake` with `<path-to-koreader-android-gcc>/arm-linux-androideabi-gcc`
and was able to successfully build cqueues for arm!

So it's possible to bulid cqueues for crosscompiler. I did stuck at some other manual compile dependencies so switched to LuaRocks, as it seems easier but now I'm also stuck. 

Please help with above error

**Comment by Frenzie** [comment]
Are you sure it's all compiled for the right target arch just by setting `CC`? (Including dependencies and all.)

**Comment by mwoz123** [comment]
I base on ["Subject: Re: How can I cross compile(to arm on x86) via rockspec?"](http://lua-users.org/lists/lua-l/2013-10/msg00338.html) : 
```
I have successfully cross-compiled rocks to ARM with LuaRocks. Instead
of editing the rockspecs themselves, edit your luarocks/config.lua
file and add something like the following:

variables = {
   CC = [[/opt/arm-2007q1/bin/arm-none-linux-gnueabi-gcc]],
   LD = [[/opt/arm-2007q1/bin/arm-none-linux-gnueabi-gcc]],
   CFLAGS = [[-L/opt/arm-2007q1/lib -I/opt/arm-2007q1/include]],
}
```

I used "-I" instead "-L" in CFLAGS as for "-L" I'd error: 
`/usr/include/lua5.3/luaconf.h:192:10: fatal error: lua5.3-deb-multiarch.h: No such file or directory`

[LuaRocks wiki: Config parameters maybe overriden in commandline](https://github.com/luarocks/luarocks/wiki/luarocks) 
"Variables from the "variables" table of the configuration file can be overriden with VAR=VALUE"

[And here cross compile is just about changing compiler](https://www.acmesystems.it/arm9_toolchain)

Unfortunately for my proposed command I'd got stuck on :
` ‘_Float128’ is not supported on this target`

**Comment by Frenzie** [comment]
Everything new would be x-compiled, yes. But depending on the specifics you might need to clean up everything first.

I may have seen something like that with some x86 objects trying to link to ARM.

**Comment by NiLuJe** [comment]
Yeah, the weird ENOFILE may indeed be a sign of arch mismatch ;).

(Much like you'd get either that or ENOEXEC when trying to *run* a binary in the wrong arch).

**Comment by mwoz123** [comment]
I didn't find  anything about cleaning build  in luarocks. Maybe it's not needed? Was that what you meant? 

To be sure I did removed `~/.luarocks` directory (so no previous builds should be in cache) and rerun command, but no changes - again `is not supported` error:(

For double check  I did switch to another user account who never compiled and error was the same for the same command `is not supported`.  

If I found right sources :
- `__float128 is available on i386, x86_64, IA-64, and hppa HP-UX, as well as on PowerPC GNU/Linux targets that enable the vector scalar (VSX) instruction set. __float128 supports the 128-bit floating type. On i386, x86_64, PowerPC, and IA-64 other than HP-UX, __float128 is an alias for _Float128. On hppa and IA-64 HP-UX, __float128 is an alias for long double.`
(source: https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html)

- https://stackoverflow.com/questions/43275160/crosss-compile-for-arm7-error-int128-is-not-supported-for-this-target


Does ARM machines does not support `float128` ?

Can those dependencies be compiled for ARM (without changing theirs code)?

Or it's not available and  can't be compiled and used in ARM?

**Comment by Frenzie** [comment]
> I didn't find anything about cleaning build in luarocks. Maybe it's not needed? Was that what you meant?

In a manner of speaking. I'm just saying that you want to make sure you've got your cables plugged in properly before you make things complicated. :-)

I would also suggest always attaching logs.

**Comment by mwoz123** [comment]
> In a manner of speaking. I'm just saying that you want to make sure you've got your cables plugged in properly before you make things complicated. :-)

Right, so basicly idea was simple. Before adding it to Koreader code, I tried to compile/build it on my local PC as x86 is that's where it gets build. 

If I'd be able to compile it here there [shouldn't be a problem with adding](https://luarocks.org/#quick-start) it to koreader

So on my ubuntu 18.04 I installed couple Lua packages (including Lua-rocks)
```
$ apt list --installed | grep lua

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

liblua5.1-0/bionic,now 5.1.5-8.1build2 amd64 [installed,automatic]
liblua5.1-0-dev/bionic,now 5.1.5-8.1build2 amd64 [installed,automatic]
liblua5.2-0/bionic,now 5.2.4-1.1build1 amd64 [installed]
liblua5.2-dev/bionic,now 5.2.4-1.1build1 amd64 [installed]
liblua5.3-0/bionic,now 5.3.3-1 amd64 [installed]
liblua5.3-dev/bionic,now 5.3.3-1 amd64 [installed]
lua-any/bionic,bionic,now 24 all [installed,automatic]
lua-sec/bionic,now 0.6-4 amd64 [installed,automatic]
lua-socket/bionic,now 3.0~rc1+git+ac3201d-4 amd64 [installed,automatic]
lua5.3/bionic,now 5.3.3-1 amd64 [installed]
luarocks/bionic,bionic,now 2.4.2+dfsg-1 all [installed]
```
last package is  LuaRocks which I used from commandline to create command for building lua-http.
I also installed `arm-linux-gnueabi-gcc` compiler.

Again command I get stuck on  is: `$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" CFLAGS="-I/usr/include/x86_64-linux-gnu -I/usr/include/lua5.3" --local`

Logs:
- lua-http compiled with [arm-linux-gnueabi-gcc_with-compat53-log.txt](https://github.com/koreader/koreader/files/2288135/arm-linux-gnueabi-gcc_with-compat53-log.txt)
- lua-http (edited rockspec, removed compat53 dependency) compiled with [arm-linux-gnueabi-gcc_without-compat53-log.txt](https://github.com/koreader/koreader/files/2288136/arm-linux-gnueabi-gcc_without-compat53-log.txt)

Logs using compiler provider in Koreader (arm-linux-androideabi-gcc) :
- lua-http compiled with [koreader-compiler-with-compat53-log.txt](https://github.com/koreader/koreader/files/2288153/koreader-compiler-with-compat53-log.txt)
- lua-http (edited rockspec, removed compat53 dependency) compiled with [koreader-compiler-without-compat53-log.txt](https://github.com/koreader/koreader/files/2288154/koreader-compiler-without-compat53-log.txt)


Can you see any light in the tunnel?

**Comment by mwoz123** [comment]
> Generally, 128bits wide types are only available on 64bits architectures (i.e., x86_64, AArch64). So, err, not us.
(That apply to integer types, no idea about this weird float one in particular).

So you're saying Lua-http can't be used/compiled for ARM ? :(((
(or at least without replacing 128 bit variables with something else)

**Comment by NiLuJe** [comment]
Probably not.

`/home/niluje/x-tools/arm-kobo-linux-gnueabihf/arm-kobo-linux-gnueabihf/include/c++/7.3.1/arm-kobo-linux-gnueabihf/bits/c++config.h`
```
/* Define if __float128 is supported on this host. */
/* #undef _GLIBCXX_USE_FLOAT128 */
```

Compare to `/usr/include/bits/floatn.h` on a *recent* x86_64 system.

**Comment by NiLuJe** [comment]
Any *sane* software should detect that and not use it when it's not supported, though.

Which makes me think you're compiling on a x86_64 host, and the test detected it on your host, instead of your target.

**Comment by NiLuJe** [comment]
Side note: x-compiling is hell.

x-compiling through a high-level language package management system is *worse* than that (and that goes from worse to nightmarishly worse, depending on the language/PMS).

**Comment by mwoz123** [comment]
:( but this brought me back to check one of my build checks

```
$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" CFLAGS="-I/usr/include/lua5.3"  --local 
Missing dependencies for http 0.2-1:
   compat53 >= 0.3 (not installed)
   cqueues >= 20161214 (not installed)
   luaossl >= 20161208 (not installed)
   basexx >= 0.2.0 (not installed)
   lpeg (not installed)
   lpeg_patterns >= 0.3, < 0.5 (not installed)
   fifo (not installed)

http 0.2-1 depends on compat53 >= 0.3 (not installed)
Installing https://luarocks.org/compat53-0.7-1.src.rock
arm-linux-gnueabi-gcc -I/usr/include/lua5.3 -I/usr/include/lua5.3 -c lutf8lib.c -o lutf8lib.o
In file included from /usr/include/lua5.3/lua.h:16:0,
                 from c-api/compat-5.3.h:10,
                 from lprefix.h:46,
                 from lutf8lib.c:10:
/usr/include/lua5.3/luaconf.h:192:10: fatal error: lua5.3-deb-multiarch.h: No such file or directory
 #include "lua5.3-deb-multiarch.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Error: Failed installing dependency: https://luarocks.org/compat53-0.7-1.src.rock - Build error: Failed compiling object lutf8lib.o
```
error here is `error: lua5.3-deb-multiarch.h: No such file` 

so not thinking too long, I did searched for lua5.3-deb-multiarch.h
```
$ find /usr -iname "lua5.3-deb-multiarch.h"
/usr/include/x86_64-linux-gnu/lua5.3-deb-multiarch.h
```
only result is
 /usr/include/**x86_64**-linux-gnu/
maybe I should search for arm version of that file?

**Comment by Frenzie** [comment]
> So you're saying Lua-http can't be used/compiled for ARM ? :(((
(or at least without replacing 128 bit variables with something else)

That seems unlikely. It's probably just some x86_64 stuff seeping through somewhere. In fact I think that first error log there quite conspicuously shows a reference to x86_64, which besides already compiled objects for a different arch is the kind of thing I was referring to in my first reply:

```
/usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h:21:36: error: '_Float128' is not supported on this target
```

So something about the includes is wrong.

You can see the same problem in the other logs:

```
/usr/include/x86_64-linux-gnu/bits/floatn.h:75:1: error: unknown machine mode '__TC__'
 typedef _Complex float __cfloat128 __attribute__ ((__mode__ (__TC__)));
 ^
/usr/include/x86_64-linux-gnu/bits/floatn.h:87:9: error: unknown type name '__float128'
 typedef __float128 _Float128;
```

**Comment by Frenzie** [comment]
To be clear, those includes should come from a location along the lines of `/usr/include/arm-linux-gnueabihf` on your standard Debubuntu cross-compile toolchain.

**Comment by mwoz123** [comment]
Thanks moving forward a bit thanks to you guys:)

based on [liblua5.1-0-dev: lua-deb-multiarch.h not found when compiling source including lua.h](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=682183) I did:
```
sudo ln -s /usr/include/x86_64-linux-gnu/lua5.1-deb-multiarch.h /usr/include/lua5.1/
pkg-config --cflags lua5.1
``` 

(last one may not be needed)
and again (with less option command):
`$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" --local`

it worked, some libs were generated, but it brings another errors that I tried to workaround:
```
sudo mkdir -p /usr/include/lua5.1/openssl
sudo ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/lua5.1/openssl/opensslconf.h
```
it was unsuccessfull yet, but some files where compiled:
```
$  find ~/.luarocks -iname *.so | xargs file
/home/marcin/.luarocks/lib/lua/5.1/bit32.so:           ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=c6418084a59a68ac2b684f203ebb35c106f13b8e, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/utf8.so:   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=0863d4d3088523bb8047003d2f2f4c58f03a0f3d, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/string.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=6382f67fef06427d20e537e9f6a6334f86dc71e3, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/table.so:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=e676ed490000941311053c3b6c828f628b13af0b, not stripped
```
_Do those files look good?_

tring to run (e.g bit32.so) on my amd64 PC gives error `Can't run binnary file: Uncorrect executable format` (my quick translation to english)

next workaround was
`sudo ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/`

Error `/usr/lib/x86_64-linux-gnu/libssl.so: file not recognized: File format not recognized` [arm-linux-gnueabi-gcc_with-ln-workarounds.txt](https://github.com/koreader/koreader/files/2290574/arm-linux-gnueabi-gcc_with-ln-workarounds.txt)

```
$ file /usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so: symbolic link to libssl.so.1.1
marcin@ubuntu:~$ file /usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so.1.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9787ff1fffe8d82268d89f6bfa3af07b3e9d140f, stripped
```
this file should be from ARM to make compile, right?

I also did some quick checks for https://github.com/dockcross/dockcross but at glance I saw no benefits over what I'm doing now

**Comment by mwoz123** [comment]
Maybe before cross compiling I should start from checking Lua-http abilities on emulator, but I didn't:/

Now wanted to check it with lua-http build (via luarocks) for x86.
But I've problems with dependecies. 

Lua-http files (installed locally in ~/.luarocks) : [lua-http-with-dependency-tree.txt](https://github.com/koreader/koreader/files/2295112/lua-http-with-dependency-tree.txt)


First step changing in news-downloader `main.lua` backend to: `local DownloadBackend = require("luahttpdownloadbackend")`

Then I added contents of `~/.luarocks/share/lua/5.1/http` directory to  new created dir `plugins/newsdownloader.koplugin/http`


Start Koreader - it fails with error:
```
08/16/18-22:10:30 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
08/16/18-22:10:30 WARN  Error when loading plugins/newsdownloader.koplugin/main.lua /usr/local/share/lua/5.1/openssl/ssl/context.lua:1: module '_openssl.ssl.context' not found:
	no field package.preload['_openssl.ssl.context']
	no file 'plugins/newsdownloader.koplugin/_openssl/ssl/context.lua'
	no file 'common/_openssl/ssl/context.lua'
	no file 'rocks/share/lua/5.1/_openssl/ssl/context.lua'
	no file 'frontend/_openssl/ssl/context.lua'
	no file './_openssl/ssl/context.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/_openssl/ssl/context.lua'
	no file '/usr/local/share/lua/5.1/_openssl/ssl/context.lua'
	no file '/usr/local/share/lua/5.1/_openssl/ssl/context/init.lua'
	no file 'plugins/newsdownloader.koplugin/lib/_openssl/ssl/context.so'
	no file 'common/_openssl/ssl/context.so'
	no file 'common/_openssl/ssl/context.dll'
	no file '/usr/lib/lua/_openssl/ssl/context.so'
	no file 'rocks/lib/lua/5.1/_openssl/ssl/context.so'
	no file './_openssl/ssl/context.so'
	no file '/usr/local/lib/lua/5.1/_openssl/ssl/context.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file 'plugins/newsdownloader.koplugin/lib/_openssl.so'
	no file 'common/_openssl.so'
	no file 'common/_openssl.dll'
	no file '/usr/lib/lua/_openssl.so'
	no file 'rocks/lib/lua/5.1/_openssl.so'
	no file './_openssl.so'
	no file '/usr/local/lib/lua/5.1/_openssl.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```
Neither adding `_openssl.so` to `plugins/newsdownloader.koplugin` nor to `plugins/newsdownloader.koplugin/common` solved the problem.

When I copied `openssl` (which contain `ssl/context.lua`) to `plugins/newsdownloader.koplugin/_openssl` (please not underscore here `_opensssl`) then I've loop error (circular dependency?) :
```
08/16/18-22:24:30 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
08/16/18-22:24:31 WARN  Error when loading plugins/newsdownloader.koplugin/main.lua plugins/newsdownloader.koplugin/_openssl/ssl/context.lua:1: loop or previous error loading module '_openssl.ssl.context'
```

Anyone could help?

**Comment by Frenzie** [comment]
> Maybe before cross compiling I should start from checking Lua-http abilities on emulator, but I didn't:/

You can do whatever you want of course. :-D

But if you really mean checking lua-http capabilities, you can just use your system's Lua + luarocks first for some simple tests. (That's what I did on GitHub downloads specifically, which currently fail in KOReader. It only takes a couple of minutes)

Then you can either already start writing KOReader code with the luarocks module from your system or dive right into the compile time stuff.

But that aside. You'll probably just want to add a few relevant paths here for quick testing within KOReader itself:

https://github.com/koreader/koreader/blob/cd37535056ed571d111cf3a732a02e5f95cbc755/setupkoenv.lua#L2-L7

**Comment by mwoz123** [comment]
For tests I've changed paths to:
```
package.path =
    "common/?.lua;rocks/share/lua/5.1/?.lua;frontend/?.lua;/home/osboxes/.luarocks/share/lua/5.1/?.lua;/home/osboxes/.luarocks/share/lua/5.1/compat53/?.lua;/home/osboxes/.luarocks/share/lua/5.1/cqueues/?.lua;/home/osboxes/.luarocks/share/lua/5.1/http/?.lua;/home/osboxes/.luarocks/share/lua/5.1/lpeg_patterns/?.lua;/home/osboxes/.luarocks/share/lua/5.1/openssl/?.lua;" ..
    package.path
package.cpath =
    "common/?.so;common/?.dll;/usr/lib/lua/?.so;rocks/lib/lua/5.1/?.so;/home/osboxes/.luarocks/lib/lua/5.1/?.so;/home/osboxes/.luarocks/lib/lua/5.1/compat53/?.so;" ..
    package.cpath
```

but then I'd huge explosion at startup: 
[fail-log.txt](https://github.com/koreader/koreader/files/2298247/fail-log.txt)

It was orcale virtual machine but I guess it doesn't make difference.

**Comment by Frenzie** [comment]
Hm, maybe there are some compatibility issues between our OpenSSL and the one in LuaRocks? Have you tried the wbuilder? (./kodev wbuilder) It loads a more minimal set of things just for building GUI widgets.

**Comment by Frenzie** [comment]
If there are docs I didn't write them. I think this little tidbit by @houqp is all there is: http://koreader.rocks/doc/topics/Hacking.md.html

There isn't much to it though. You just add/include whatever you want to play around with to tools/wbuilder.lua so you can iterate on it more quickly than in the normal program workflow.

You're dealing with an awful lot of dependencies unfortunately, but there's a small chance it'd help to play around with some stuff without having to fix all that first.

**Comment by mwoz123** [comment]
Hmm even if it will work with 'wbuilder' we need to find a way to make it work with full application:/

> there's a small chance it'd help to play around with some stuff without having to fix all that first.

What you mean by "fix all that first"?

Do we know how this can be fixed?

Are we sure its problem with `open ssl`?

If we 'd compiled lua-http and dependencies with koreader open ssl version would have worked?

**Comment by Frenzie** [comment]
I mean that writing KOReader-specific code that uses something is only vaguely related to making everything build as it should. Particularly if you're just giving something a quick try to see if it could be interesting or does what you want it to do there's not much point to wasting time on building things, but you can also have frontend code that's ready to go in anticipation of backend changes, etc. etc.

> Do we know how this can be fixed?

For Android, who knows. For Windows, doubtful. For Mac, possibly with minor difficulty. For everything else, it's hard for things not to work. ;-)

**Comment by Frenzie** [comment]
Luasec 0.8 combined with up-to-date Luasocket now implement redirects. Closing.
