### PR TITLE
Unbreak macOS build

### LINKED ISSUE #7307: macos build broken by commit 5df25f8
* KOReader version: 2021.02 pre-release nightlies
* Device:  MacOS development build

#### Issue

As of commit 5df25f8bd60d17d7547d75b019082ae5edd65f38, the macos build is broken, with the following error:

```
[ 12%] Linking CXX executable sdcv
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_iconv_open", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
My best guess, looking at the diffs, is that it's the change from GetText 0.20.1 to 0.21 in base commit b1abca63443875ab9aeea83097611c50bee4de69

#### Steps to reproduce

Check out any commit on master at or after the referenced commit, run kodev build

### PR DESCRIPTION
**Pull request by NiLuJe**
Fix #7307

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader/7313)

### CODE REVIEW

**Comment by rexkerr** [comment]
That worked, thanks!
