### ISSUE TITLE
PDF text select/highlight crash: 'struct Color8' has no member named 'r'

### ISSUE THREAD

**Issue by zeeyado** [koreader/koreader#15918]
**Device**
Boox page (b&w)
Android 11 
v2026.07.2

**Description/repro**
Select text in a PDF with "Write highlights into PDF" enabled, then press Select or Highlight. KOReader exits:

```
V/KOReader: save highlight
V/KOReader: write to pdf document save { color = "gray", drawer = "lighten", ... }
E/NativeThread: Failed to run script: ffi/mupdf.lua:763: 'struct Color8' has no member named 'r'
```

`ffi/mupdf.lua addMarkupAnnotation` indexes `bb_color.r/.g/.b` unconditionally in all three branches, so a luminance-only color (Color8, only `.a`) is a hard error, and it is uncaught, so KOReader exits. Colored highlights are fine.

Workaround: use a colored highlight or just turn off Write highlights into PDF""

Couldn't reproduce on macos, the color is "gray" which is what `saved_color` becomes on b&w (readerview.lua: `Screen:isColorEnabled() and "yellow" or "gray"`). On desktop with the same gray setting there is no crash and the annotation is actually written as yellow, which looks like `colorFromName("gray")` returning nil there and falling through to the default.

**Comment by hius07** [comment]
Already fixed in recent nightly builds.

**Comment by zeeyado** [comment]
I'm still reproducing this on latest.

From what I can see this is caused by #15676 which moved color resolution to the caller so gray now reaches `addMarkupAnnotation` as a `Color8`, and `bb_color.r` will raise

before that, pdfdocument.lua resolved color itself `local annot_color = item.color and BlitBuffer.colorFromName(item.color)`

*Edit: and i guess it was always falling through to yellow, HIGHLIGHT_COLORS has no gray, and I think on macos I was an a build predating the PR above so that caused some confusion, and also explains why I didn't notice on b&w device since it was just "yellow"

**Comment by zeeyado** [comment]
Yeah I fetched latest macos build -83 and it's there:

failed to run lua chunk: ./ffi/mupdf.lua:763: 'struct Color8' has no member named 'r'

**Comment by zeeyado** [comment]
Repro steps for clarity:

1. Open a PDF
2. Enable "Write highlights into PDF"
3. Set the highlight color to Gray
4. Select text, press select or highlight

**Comment by hius07** [comment]
Sorry, not yet. It's similar to https://github.com/koreader/koreader/pull/15790. Will do, thanks.
